spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/documents
    username: documents_user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

batch:
  size: 5